-- MySQL Script generated by MySQL Workbench
-- 04/23/15 12:41:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- Nasza baza.

-- -----------------------------------------------------
-- Schema mydb
--
-- Nasza baza.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_polish_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Uzytkownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Uzytkownicy` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `Login` VARCHAR(45) NOT NULL,
  `Haslo` VARCHAR(45) NOT NULL,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Plec` TINYINT(1) NULL,
  `Data_urodzenia` DATE NULL,
  `Miejsce_zamieszkania` VARCHAR(45) NULL,
  `Adres_email` VARCHAR(45) NULL,
  `Data_zalozenia_konta` DATE NULL,
  `Zamieszczone_ankiety` INT NULL,
  `Administrator` TINYINT(1) NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ankiety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ankiety` (
  `idAnkiety` INT NOT NULL AUTO_INCREMENT,
  `Uzytkownicy_idUsers` INT NOT NULL,
  PRIMARY KEY (`idAnkiety`, `Uzytkownicy_idUsers`),
  INDEX `fk_Ankiety_Uzytkownicy_idx` (`Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Ankiety_Uzytkownicy`
    FOREIGN KEY (`Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Uzytkownicy` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ankietowany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ankietowany` (
  `idAnkietowany` INT NOT NULL AUTO_INCREMENT,
  `Imie` VARCHAR(45) NULL,
  `Nazwisko` VARCHAR(45) NULL,
  `Wypelnione_ankiety` VARCHAR(45) NULL,
  PRIMARY KEY (`idAnkietowany`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zaproszenia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zaproszenia` (
  `idZaproszenia` INT NOT NULL AUTO_INCREMENT,
  `Tytul_ankiety` VARCHAR(45) NULL,
  `Krotki_opis` VARCHAR(45) NULL,
  `Ankiety_idAnkiety` INT NOT NULL,
  `Ankiety_Uzytkownicy_idUsers` INT NOT NULL,
  `Ankietowany_idAnkietowany` INT NOT NULL,
  PRIMARY KEY (`idZaproszenia`, `Ankiety_idAnkiety`, `Ankiety_Uzytkownicy_idUsers`, `Ankietowany_idAnkietowany`),
  INDEX `fk_Zaproszenia_Ankiety1_idx` (`Ankiety_idAnkiety` ASC, `Ankiety_Uzytkownicy_idUsers` ASC),
  INDEX `fk_Zaproszenia_Ankietowany1_idx` (`Ankietowany_idAnkietowany` ASC),
  CONSTRAINT `fk_Zaproszenia_Ankiety1`
    FOREIGN KEY (`Ankiety_idAnkiety` , `Ankiety_Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Ankiety` (`idAnkiety` , `Uzytkownicy_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Zaproszenia_Ankietowany1`
    FOREIGN KEY (`Ankietowany_idAnkietowany`)
    REFERENCES `mydb`.`Ankietowany` (`idAnkietowany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wiadomosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wiadomosci` (
  `idWiadomosci` INT NOT NULL AUTO_INCREMENT,
  `Tresc_wiad` VARCHAR(45) NULL,
  `Wiad_od` VARCHAR(45) NULL,
  `Wiad_do` VARCHAR(45) NULL,
  `Data` DATE NULL,
  `Temat` VARCHAR(45) NULL,
  `Uzytkownicy_idUsers` INT NOT NULL,
  PRIMARY KEY (`idWiadomosci`, `Uzytkownicy_idUsers`),
  INDEX `fk_Wiadomosci_Uzytkownicy1_idx` (`Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Wiadomosci_Uzytkownicy1`
    FOREIGN KEY (`Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Uzytkownicy` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pytania`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pytania` (
  `idPytania` INT NOT NULL AUTO_INCREMENT,
  `Tresc` VARCHAR(45) NULL,
  `Ankiety_idAnkiety` INT NOT NULL,
  `Ankiety_Uzytkownicy_idUsers` INT NOT NULL,
  PRIMARY KEY (`idPytania`, `Ankiety_idAnkiety`, `Ankiety_Uzytkownicy_idUsers`),
  INDEX `fk_Pytania_Ankiety1_idx` (`Ankiety_idAnkiety` ASC, `Ankiety_Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Pytania_Ankiety1`
    FOREIGN KEY (`Ankiety_idAnkiety` , `Ankiety_Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Ankiety` (`idAnkiety` , `Uzytkownicy_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odp_otwarta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odp_otwarta` (
  `idOdp_otwarta` INT NOT NULL AUTO_INCREMENT,
  `Tresc` VARCHAR(45) NULL,
  `Pytania_idPytania` INT NOT NULL,
  `Pytania_Ankiety_idAnkiety` INT NOT NULL,
  `Pytania_Ankiety_Uzytkownicy_idUsers` INT NOT NULL,
  PRIMARY KEY (`idOdp_otwarta`, `Pytania_idPytania`, `Pytania_Ankiety_idAnkiety`, `Pytania_Ankiety_Uzytkownicy_idUsers`),
  INDEX `fk_Odp_otwarta_Pytania1_idx` (`Pytania_idPytania` ASC, `Pytania_Ankiety_idAnkiety` ASC, `Pytania_Ankiety_Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Odp_otwarta_Pytania1`
    FOREIGN KEY (`Pytania_idPytania` , `Pytania_Ankiety_idAnkiety` , `Pytania_Ankiety_Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Pytania` (`idPytania` , `Ankiety_idAnkiety` , `Ankiety_Uzytkownicy_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odp_zamknieta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odp_zamknieta` (
  `idOdp_zamknieta` INT NOT NULL AUTO_INCREMENT,
  `Tresc` VARCHAR(45) NULL,
  `Pytania_idPytania` INT NOT NULL,
  `Pytania_Ankiety_idAnkiety` INT NOT NULL,
  `Pytania_Ankiety_Uzytkownicy_idUsers` INT NOT NULL,
  PRIMARY KEY (`idOdp_zamknieta`, `Pytania_idPytania`, `Pytania_Ankiety_idAnkiety`, `Pytania_Ankiety_Uzytkownicy_idUsers`),
  INDEX `fk_Odp_zamknieta_Pytania1_idx` (`Pytania_idPytania` ASC, `Pytania_Ankiety_idAnkiety` ASC, `Pytania_Ankiety_Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Odp_zamknieta_Pytania1`
    FOREIGN KEY (`Pytania_idPytania` , `Pytania_Ankiety_idAnkiety` , `Pytania_Ankiety_Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Pytania` (`idPytania` , `Ankiety_idAnkiety` , `Ankiety_Uzytkownicy_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Wypelnione_ankiety`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Wypelnione_ankiety` (
  `idWypelnione_ankiety` INT NOT NULL AUTO_INCREMENT,
  `Ankietowany_idAnkietowany` INT NOT NULL,
  PRIMARY KEY (`idWypelnione_ankiety`, `Ankietowany_idAnkietowany`),
  INDEX `fk_Wypelnione_ankiety_Ankietowany1_idx` (`Ankietowany_idAnkietowany` ASC),
  CONSTRAINT `fk_Wypelnione_ankiety_Ankietowany1`
    FOREIGN KEY (`Ankietowany_idAnkietowany`)
    REFERENCES `mydb`.`Ankietowany` (`idAnkietowany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Odp_zamknieta_has_Ankietowany`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Odp_zamknieta_has_Ankietowany` (
  `Odp_zamknieta_idOdp_zamknieta` INT NOT NULL,
  `Odp_zamknieta_Pytania_idPytania` INT NOT NULL,
  `Odp_zamknieta_Pytania_Ankiety_idAnkiety` INT NOT NULL,
  `Odp_zamknieta_Pytania_Ankiety_Uzytkownicy_idUsers` INT NOT NULL,
  `Ankietowany_idAnkietowany` INT NOT NULL,
  PRIMARY KEY (`Odp_zamknieta_idOdp_zamknieta`, `Odp_zamknieta_Pytania_idPytania`, `Odp_zamknieta_Pytania_Ankiety_idAnkiety`, `Odp_zamknieta_Pytania_Ankiety_Uzytkownicy_idUsers`, `Ankietowany_idAnkietowany`),
  INDEX `fk_Odp_zamknieta_has_Ankietowany_Ankietowany1_idx` (`Ankietowany_idAnkietowany` ASC),
  INDEX `fk_Odp_zamknieta_has_Ankietowany_Odp_zamknieta1_idx` (`Odp_zamknieta_idOdp_zamknieta` ASC, `Odp_zamknieta_Pytania_idPytania` ASC, `Odp_zamknieta_Pytania_Ankiety_idAnkiety` ASC, `Odp_zamknieta_Pytania_Ankiety_Uzytkownicy_idUsers` ASC),
  CONSTRAINT `fk_Odp_zamknieta_has_Ankietowany_Odp_zamknieta1`
    FOREIGN KEY (`Odp_zamknieta_idOdp_zamknieta` , `Odp_zamknieta_Pytania_idPytania` , `Odp_zamknieta_Pytania_Ankiety_idAnkiety` , `Odp_zamknieta_Pytania_Ankiety_Uzytkownicy_idUsers`)
    REFERENCES `mydb`.`Odp_zamknieta` (`idOdp_zamknieta` , `Pytania_idPytania` , `Pytania_Ankiety_idAnkiety` , `Pytania_Ankiety_Uzytkownicy_idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Odp_zamknieta_has_Ankietowany_Ankietowany1`
    FOREIGN KEY (`Ankietowany_idAnkietowany`)
    REFERENCES `mydb`.`Ankietowany` (`idAnkietowany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
